// A hardcoded pool of character archetypes. When the user hits an
// auto-generate button, one of these is picked at random and given to the
// LLM as a concrete seed — without it, the model tends to default to the
// same "most probable" generic character every time.

export const ARCHETYPES = [
  "volcanic fire-forged blacksmith warrior",
  "deep-sea bioluminescent psychic",
  "storm-riding sky pirate",
  "crystal golem shaman",
  "void-touched shadow assassin",
  "overgrown jungle beast-tamer",
  "cybernetic mech-armor soldier",
  "ice-bound frost druid",
  "sand-dwelling desert nomad warrior",
  "insectoid hive-mind scout",
  "bioluminescent fungal forest spirit",
  "gravity-manipulating astral monk",
  "living-metal construct guardian",
  "venomous swamp witch doctor",
  "solar-powered radiant priestess",
  "subterranean tunneling miner-beast",
  "electric eel-like storm conjurer",
  "ash-covered wasteland scavenger",
  "coral reef merfolk healer",
  "meteor-forged armored knight",
  "wind-dancing aerial acrobat warrior",
  "root-bound tree-spirit elder",
  "nebula-born starlight wanderer",
  "molten lava serpent rider",
  "frost-crystal ice sculptor mage",
  "rust-belt scrapyard engineer",
  "bone-armored necromancer",
  "bioluminescent cave-dwelling explorer",
  "thunderstorm-summoning tribal chieftain",
  "sandstone golem temple guardian",
  "toxic spore mushroom forager",
  "deep-space void hunter",
  "crystal-eyed oracle seer",
  "feral wolf-pack alpha",
  "steam-powered airship captain",
  "glacier-carving ice knight",
  "volcanic ash phoenix keeper",
  "underground fungal network gardener",
  "magnetic-field manipulating tech mystic",
  "coral-spined reef warrior",
  "sky-temple monk with wind magic",
  "obsidian-clawed shadow beast",
  "bioluminescent jellyfish dancer",
  "ember-forged desert blacksmith",
  "storm-eyed lightning duelist",
  "moss-covered ancient guardian tree-being",
  "quartz-veined crystal miner",
  "deep-jungle vine-whip hunter",
  "solar-flare forged sun warrior",
  "permafrost-preserved ancient beast",
];

export function randomArchetype() {
  return ARCHETYPES[Math.floor(Math.random() * ARCHETYPES.length)];
}
