// ---------------------------------------------------------------------------
// EDIT ME: this is the "bigger prompt" that fixes the Relics art style. The
// per-character description generated by the LLM gets dropped into it before
// being sent to the image model. Replace ART_STYLE_TEMPLATE with your own
// art-direction prompt whenever you're ready — everything else keeps working.
// ---------------------------------------------------------------------------
const ART_STYLE_TEMPLATE = `Premium digital trading card game illustration, painterly concept-art style blending fantasy and sci-fi, dramatic cinematic lighting with strong rim light, rich saturated color palette, intricate costume and material detail, dynamic heroic pose, epic atmospheric background with depth and scale, sharp focus on the subject with soft atmospheric depth in the background, high-detail brushwork like AAA game splash art. No text, no watermark, no logo, no border. Vertical trading-card composition.`;

const TIER_FLAVOR = {
  normal:
    "Grounded, mortal-scale presence — impressive and skilled, but believable as a denizen of their world.",
  legend:
    "Aura of immense, battle-worn power; weathered gear or ancient artifacts, scars of a legendary past, a larger-than-life presence radiating faint magical or technological energy.",
  myth:
    "Otherworldly, almost unreal presence; features partly obscured or ambiguous, reality-bending visual cues, an overwhelming aura suggesting a being beyond mortal comprehension.",
};

export function buildImagePrompt(description, tier) {
  const flavor = TIER_FLAVOR[tier] || TIER_FLAVOR.normal;
  return `${ART_STYLE_TEMPLATE}\n\n${flavor}\n\nCharacter: ${description}`;
}
